apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
  - name: shell
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    stdin: true
    tty: true
