apiVersion: v1
kind: Pod
metadata:
  name: cm-command-pod
spec:
  containers:
  - name: cm-command-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/sh", "-c", "echo $(SPECIAL_HOW_KEY) $(SSPECIAL_TYPE_KEY)"]
    env:
      - name: SPECIAL_HOW_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.how
      - name: SPECIAL_TYPE_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.type
  restartPolicy: Never
    
