apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-word
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-word
  template:
    metadata:
      labels:
        app: hello-word
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80