apiVersion: v1
kind: Pod
metadata:
  name: host-path-volume-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /cache
        name: test-volume
  - name: busybox-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep 36000"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /test
        name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        path: /data
        type: Directory

