apiVersion: v1
kind: Pod
metadata:
  name: start-stop-pod
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo hello from the postStart headler > /usr/share/message"]
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo hello from the preStop headler > /usr/share/message"]