apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-secret-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volume-secret
  template:
    metadata:
      labels:
        app: volume-secret
    spec:
      containers:
      - name: volume-secret-container
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: user-pwd-secret
            mountPath: "/etc/secrets"
      volumes:
        - name: user-pwd-secret
          secret:
            secretName: user-pwd-secret
