apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron-job
  labels:
    app: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-container
            image: busybox
            imagePullPolicy: IfNotPresent
            args: ["/bin/sh", "-c", "date; echo Hello from the k8s cluster"]
          restartPolicy: OnFailure