apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
  labels:
    app: pi
spec:
  template:
    metadata:
      name: pi-pod
      labels:
        app: pi
    spec:
      containers:
      - name: pi-container
        image: perl
        imagePullPolicy: IfNotPresent
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never